version: '3'


volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}


services:
  db:
    build: ./dockerconfig/postgres
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups
    environment:
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
  web:
    build: .
    command: /start.sh
    depends_on:
      - db
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    links:
      - db